kind: pipeline
name: packer

steps:
- name: build-ubuntu
  image: hashicorp/packer
  commands:
     - packer build -force -only=vsphere-iso -var-file=variables.json -var-file=./ubuntu/20.04/server/template.json ./ubuntu/20.04/server/ubuntu.json
  environment:
    VCENTER_SERVER:
      from_secret: vcenter_server
    VCENTER_USERNAME:  
      from_secret: vcenter_username
    VCENTER_PASSWORD:
      from_secret: vcenter_password
    VSPHERE_CLUSTER:
      from_secret: vsphere_cluster
    DATASTORE:
      from_secret: datastore
    NETWORK:
      from_secret: network

- name: build-windows-core
  image: hashicorp/packer
  commands:
     - packer build -force -only=vsphere-iso -var-file=variables.json -var-file=./windows/2019/server/template.json ./windows/2019/server/windows-core.json
  environment:
    VCENTER_SERVER:
      from_secret: vcenter_server
    VCENTER_USERNAME:  
      from_secret: vcenter_username
    VCENTER_PASSWORD:
      from_secret: vcenter_password
    VSPHERE_CLUSTER:
      from_secret: vsphere_cluster
    DATASTORE:
      from_secret: datastore
    NETWORK:
      from_secret: network

- name: build-windows-gui
  image: hashicorp/packer
  commands:
     - packer build -force -only=vsphere-iso -var-file=variables.json -var-file=./windows/2019/server/template.json ./windows/2019/server/windows-gui.json
  environment:
    VCENTER_SERVER:
      from_secret: vcenter_server
    VCENTER_USERNAME:  
      from_secret: vcenter_username
    VCENTER_PASSWORD:
      from_secret: vcenter_password
    VSPHERE_CLUSTER:
      from_secret: vsphere_cluster
    DATASTORE:
      from_secret: datastore
    NETWORK:
      from_secret: network

- name: teams-webhook
  image: jdamata/drone-teams
  settings:
    webhook: 
      from_secret: WEBHOOK
